#/*
# *  ***************************************
# *  * @author Gihan Liyanage
# *  * @date Aug 12, 2022 - 12:07:22 AM
# *  ***************************************
# */

spring.application.name=CRIB-PdfGeneratorMS
server.port=8015

# ===============================
# = JPA / HIBERNATE
# ===============================

springdoc.show-actuator=true
management.endpoints.web.exposure.include=health,info

# ===============================
# Microservices
# ===============================

microservice.commonUtils.url=http://CRIB-CommonUtilsMS
microservice.consumer.url=http://CRIB-ConsumerMS
microservice.corporate.url=http://CRIB-CorporateMS