#/*
# *  ***************************************
# *  * @author Gihan Liyanage
# *  * @date Aug 12, 2022 - 12:07:22 AM
# *  ***************************************
# */

spring.application.name=CRIB-ConsumerMS
server.port=8013

# ===============================
# = DATA SOURCE
# ===============================

spring.datasource.url=jdbc:sqlserver://192.168.50.47:1433;databaseName=PAM
spring.datasource.username=sa
spring.datasource.password=nable@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# = JPA / HIBERNATE
# ===============================

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.default_schema=dbo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
#spring.jpa.properties.hibernate.jdbc.batch_size=20


spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.ddl-auto=update


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


springdoc.show-actuator=true
management.endpoints.web.exposure.include=health,info

# ===============================
# CRIB API WSDL File
# ===============================

crib.wsdl.url=classpath:wsdl/LiveRequestinvoker.wsdl


crib.cons.s_consumerDetails=DATAPACKET/BODY/CONSUMER_PROFILE_VER4/CONSUMER_DETAILS_VER4
crib.cons.s_identificationDetails=DATAPACKET/BODY/CONSUMER_PROFILE_VER4/CONSUMER_DETAILS_VER4/IDENTIFICATION_DETAILS_VER4
crib.cons.s_mailingAddresses=DATAPACKET/BODY/CONSUMER_ADDRESS_VER4/MAILING_ADDRESS_VER4
crib.cons.s_permanentAddresses=DATAPACKET/BODY/CONSUMER_ADDRESS_VER4/PERMANENT_ADDRESS_VER4
crib.cons.s_reportedNames=DATAPACKET/BODY/CONSUMER_NORMAL_NAMES_VER4/NAMES_VER4
crib.cons.s_employmentDetails=DATAPACKET/BODY/CONSUMER_EMPLOYMENT_VER4/EMPLOYMENT_DETAILS_VER4
crib.cons.s_relationships=DATAPACKET/BODY/CONSUMER_RELATIONSHIPS_VER4/RELATIONSHIP_DETAILS_VER4
crib.cons.s_relationshipAddresses=DATAPACKET/BODY/hh
crib.cons.s_settledCFDetils=DATAPACKET/BODY/CONSUMER_SETTLED_CREDIT_SUMMARY_DETAILS_VER1/CONS_SETTLED_SUMMARY_DETAILS_VER1
crib.cons.s_settledCFSummary=DATAPACKET/BODY/CONSUMER_SETTLED_CREDIT_SUMMARY_VER4/CONS_SETTLED_SUMMARY_VER4
crib.cons.s_lendingInstInquiries=DATAPACKET/BODY/CONSUMER_INQUIRY_VER4/INQUIRY_DETAILS_VER4
crib.cons.s_inqBySubject=DATAPACKET/BODY/CONSUMER_INQUIRY_VER4/INQUIRY_DETAILS_VER4
crib.cons.s_creditFacility=DATAPACKET/BODY/CONSUMER_CREDIT_FACILITY_VER8/MASTER_CREDIT_DETAILS_VER4
crib.cons.s_cFDetails=DATAPACKET/BODY/CONSUMER_CREDIT_FACILITY_VER8/MASTER_CREDIT_DETAILS_VER4/CREDIT_DETAILS_VER4
crib.cons.s_last24Months=DATAPACKET/BODY/CONSUMER_CREDIT_FACILITY_VER8/MASTER_CREDIT_DETAILS_VER4/MONTH_YEAR_VER4
crib.cons.s_cfFor24Months=DATAPACKET/BODY/CONSUMER_CREDIT_FACILITY_VER8/MASTER_CREDIT_DETAILS_VER4/MONTH_YEAR_VER4/CONSUMER_HISTORY_SUMMARY_VER4
crib.cons.s_disputeDetails=DATAPACKET/BODY/CONSUMER_CF_DISPUTE_VER4
crib.cons.s_potAndCurrLiabilitiesHeader=DATAPACKET/BODY/CREDIT_SUMMARY_VER4/CURRENCY_VER4
crib.cons.s_potAndCurrLiabilities=DATAPACKET/BODY/CREDIT_SUMMARY_VER4/CURRENCY_VER4/SUMMARY_VER4
crib.cons.s_cFOfGlanceStatus=DATAPACKET/BODY/CONSUMER_CREDIT_FACILITY_STATUS_VER4/CONSUMER_CREDIT_FACILITY_STATUS_VER4
crib.cons.s_dishonChequeSummary=DATAPACKET/BODY/CONSUMER_DC_SUMMARY_VER4/DISHONOURED_CHEQUE_SUMM_VER4
crib.cons.s_dishonChequeDetails=DATAPACKET/BODY/CONSUMER_DC_DETAILS_VER4/DC_DETAILS_VER4
crib.cons.s_catalogueDescription=DATAPACKET/BODY/CONSUMER_CREDIT_FACILITY_CATALOGUE_VER4/CONSUMER_CREDIT_DETAILS_CATALOGUE_VER4


crib.apiUsername=gihan
crib.apiPassword=nable@123
crib.encryptionKey=asdf-9kjh-qwe56
crib.decryptionKey=tbkw-3hm8-soz19

# ===============================
# Microservices
# ===============================

microservice.commonUtils.url=http://CRIB-CommonUtilsMS
